apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: docker-kubectl-agent
spec:
  serviceAccountName: jenkins-agent
  containers:
  - name: docker
    image: docker:24.0.7-cli
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.25.4
    command: ["cat"]
    tty: true
    volumeMounts:
    - mountPath: /root/.kube/config
      name: kubeconfig

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket

  - name: kubeconfig
    hostPath:
      path: /etc/rancher/k3s/k3s.yaml
      type: File
