#THIS IS A TEMPLATE

version: "3.9"

networks:
  jenkins-network:

services:
  jenkins-master:
    image: jenkins/jenkins
    container_name: jenkins-master
    user: root
    ports:
      - "30000:8080"
      - "50000:50000"
    volumes:
      - "${HOME}/jenkins_home:/var/jenkins_home"
    networks:
      - jenkins-network

  docker-agent:
    image: jenkins/inbound-agent
    container_name: docker-agent
    restart: always
    user: root
    networks:
      - jenkins-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
    environment:
      JENKINS_AGENT_NAME: ""   
      JENKINS_URL: ""          
      JENKINS_SECRET: ""       
